const BRANDS = [
  'Audemars Piguet',
  'Baraka',
  'Bibigi',
  'Bvlgari',
  'Carrera y Carrera',
  'Cartier',
  'Casato',
  'Chaumet',
  'Chopard',
  'Damiani',
  'De Beers',
  'De Grisogono',
  'Faberge',
  'Franck Muller',
  'Giorgio Visconti',
  'Imma',
  'Jacob & Co',
  'Mikimoto',
  'Pasquale Bruni',
  'Piaget',
  'Roberto Coin',
  'Pomellato',
  'Roberto Coin',
  'Stephen Webster',
  'Tiffany & Co',
  'Van Cleef & Arpels',
  'ЭПЛ Якутские бриллианты',
  "Русские самоцветы"
];

export default BRANDS;